// showcases/react-showcase/src/components/form/input.tsx
import { DBInput } from '@db-ui/react-components/src';
import { useState } from 'react';
import FormWrapper from './form-wrapper';

const FormInputs = () => {
	const [controlled, setControlled] = useState('test1');
	const [uncontrolled, setUncontrolled] = useState('test2');

	return (
		<FormWrapper controlled={controlled} uncontrolled={uncontrolled}>
			<DBInput
				label="Controlled"
				placeholder="Placeholder"
				message="Description"
				icon="person"
				name="input-name"
				value={controlled}
				onChange={(event) => {
					setControlled(event.target.value);
				}}
			/>
			<DBInput
				label="Uncontrolled"
				placeholder="Placeholder"
				message="Description"
				icon="person"
				name="input-name"
				defaultValue={uncontrolled}
				onChange={(event) => {
					setUncontrolled(event.target.value);
				}}
			/>
			<DBInput
				label="Test label"
				variant="floating"
				invalidMessage="Test message"
				validMessage=""
				required
			/>
		</FormWrapper>
	);
};

export default FormInputs;

// showcases/vue-showcase/src/components/input/Input.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/input.json";
import {
	DBInput,
	LabelVariantType,
	ValueLabelType
} from "../../../../../output/vue/src";

const getDataList = (
	variant?: LabelVariantType
): string[] | ValueLabelType[] => {
	if (variant === "floating") {
		return ["Test 1", "Test 2"];
	}

	return [
		{ value: "test1", label: "Test 1" },
		{ value: "test2", label: "Test 2" }
	];
};
</script>

<template>
	<DefaultComponent title="DBInput" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInput
				:variant="exampleProps?.variant"
				:label="exampleProps?.label"
				:message="exampleProps?.message"
				:placeholder="exampleName"
				:minLength="exampleProps?.minLength"
				:required="exampleProps?.required"
				:type="exampleProps?.type"
				:disabled="exampleProps?.disabled"
				:readOnly="exampleProps?.readOnly"
				:value="exampleProps?.value"
				:icon="exampleProps?.icon"
				:iconAfter="exampleProps?.iconAfter"
				:dataList="
					exampleProps?.dataList
						? getDataList(exampleProps?.variant)
						: undefined
				"
			></DBInput>
		</template>
	</DefaultComponent>
</template>
