// showcases/vue-showcase/src/components/infotext/Infotext.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/infotext.json";
import { DBInfotext } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBInfotext" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext
				:size="exampleProps.size"
				:variant="exampleProps.variant"
				:icon="exampleProps.icon"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/infotext/index.tsx
import { DBInfotext } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/infotext.json';
import { type DBInfotextProps } from '../../../../../output/react/src/components/infotext/model';
import { getVariants } from '../data';

const getInfotext = ({ variant, size, icon, children }: DBInfotextProps) => (
	<DBInfotext variant={variant} size={size} icon={icon}>
		{children}
	</DBInfotext>
);

const InfotextComponent = () => {
	return (
		<DefaultComponent
			title={'DBInfotext'}
			variants={getVariants(
				defaultComponentVariants,
				getInfotext
			)}></DefaultComponent>
	);
};

export default InfotextComponent;
