// showcases/vue-showcase/src/components/form/Textareas.vue
<script setup lang="ts">
import FormWrapper from "./FormWrapper.vue";
import { DBTextarea } from "../../../../../output/vue/src";
import { ref } from "vue";

const plain = ref("test1");
const vModel = ref("test2");
</script>

<template>
	<FormWrapper :plain="plain" :vmodel="vModel">
		<DBTextarea
			label="Plain"
			placeholder="Placeholder"
			message="Description"
			icon="person"
			name="textarevalue-name"
			:value="plain"
			@change="plain = $event.target.value"
		/>
		<DBTextarea
			label="VModel"
			placeholder="Placeholder"
			message="Description"
			icon="person"
			name="textarea-name"
			v-model:value="vModel"
		/>
	</FormWrapper>
</template>

// showcases/angular-showcase/src/app/components/form/textareas/textareas.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { WrapperComponent } from '../wrapper/wrapper.component';
import { DBTextarea } from '../../../../../../../output/angular/src';

@Component({
	selector: 'app-textareas',
	standalone: true,
	imports: [WrapperComponent, DBTextarea, FormsModule, ReactiveFormsModule],
	templateUrl: './textareas.component.html',
	schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
export class TextareasComponent {
	plain = 'test1';
	ngModel = 'test2';
	formControl: FormControl = new FormControl('test3');
}

<app-form-wrapper
	[plain]="plain"
	[model]="ngModel"
	[control]="formControl.value"
>
	<fieldset>
		<legend>Different form approaches</legend>
		<db-textarea
			label="Plain"
			placeholder="Placeholder"
			message="Description"
			name="textarea-name"
			[value]="plain"
			(change)="plain = $event.target.value"
		/>
		<db-textarea
			label="ngModel"
			placeholder="Placeholder"
			message="Description"
			name="textarea-name"
			[(ngModel)]="ngModel"
		/>
		<db-textarea
			label="formControl"
			placeholder="Placeholder"
			message="Description"
			name="textarea-name"
			[formControl]="formControl"
		/>
	</fieldset>
</app-form-wrapper>
