// showcases/nuxt-showcase/src/NavItemComponent.vue
<script setup lang="ts">
import { DBNavigationItem } from "../../../output/vue/src";
import { type NavItem } from "./utils/navigation-items";

defineProps<{
	navItem: NavItem;
}>();
</script>

<template>
	<DBNavigationItem :backButtonText="`Back to ${navItem.label}`">
		<template v-if="navItem.subNavigation" v-slot:subnavigation>
			<template v-for="item of navItem.subNavigation">
				<NavItemComponent :navItem="item"></NavItemComponent>
			</template>
		</template>
		<nuxt-link
			v-if="navItem.component"
			:to="navItem.path"
			ariaCurrentValue="page"
		>
			{{ navItem.label }}
		</nuxt-link>
		<template v-if="!navItem.component">{{ navItem.label }}</template>
	</DBNavigationItem>
</template>

// showcases/react-showcase/src/navigation/nav-item.tsx
import { Link, useLocation } from 'react-router-dom';
import { DBNavigationItem } from '../../../../output/react/src';
import type { NavigationItem } from '../utils/navigation-item';

const NavItem = ({ navItem }: { navItem: NavigationItem }) => {
	const location = useLocation();

	const isActive =
		navItem.path === ''
			? location.pathname === '/'
			: location.pathname.includes(navItem.path);

	return (
		<DBNavigationItem
			active={isActive}
			backButtonText={`Back to ${navItem.label}`}
			slotSubNavigation={
				navItem.subNavigation && (
					<>
						{navItem.subNavigation
							.map((subItem: NavigationItem) => ({
								...subItem,
								path: `${navItem.path}/${subItem.path}`
							}))
							.map((subItem: NavigationItem) => (
								<NavItem
									key={`router-path-${subItem.path}`}
									navItem={subItem}></NavItem>
							))}
					</>
				)
			}>
			{navItem.component ? (
				<Link key={`router-path-${navItem.path}`} to={navItem.path}>
					{navItem.label}
				</Link>
			) : (
				navItem.label
			)}
		</DBNavigationItem>
	);
};

export default NavItem;
