// showcases/vue-showcase/src/components/radio/Radio.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/radio.json";
import { DBCheckbox, DBRadio } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBRadio" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBRadio
				:label="exampleProps.label"
				:size="exampleProps.size"
				:name="exampleProps.name"
				:checked="exampleProps.checked"
				:invalid="exampleProps.invalid"
				:value="exampleProps.value"
				:required="exampleProps.required"
				:labelVariant="exampleProps.labelVariant"
				:disabled="exampleProps.disabled"
			>
				{{ exampleName }}
			</DBRadio>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/radio/index.tsx
import { DBRadio } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import { getVariants } from '../data';
import defaultComponentVariants from '../../../../shared/radio.json';
import { type DBRadioProps } from '../../../../../output/react/src/components/radio/model';

const getRadio = ({
	label,
	size,
	name,
	checked,
	invalid,
	required,
	children,
	disabled,
	value,
	labelVariant
}: DBRadioProps) => (
	<DBRadio
		label={label}
		size={size}
		name={name}
		checked={checked}
		invalid={invalid}
		required={required}
		disabled={disabled}
		labelVariant={labelVariant}
		value={value}>
		{children}
	</DBRadio>
);

const RadioComponent = () => {
	return (
		<DefaultComponent
			title={'DBRadio'}
			variants={getVariants(
				defaultComponentVariants,
				getRadio
			)}></DefaultComponent>
	);
};

export default RadioComponent;
