// showcases/vue-showcase/src/components/multi-select/MultiSelect.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/multi-select.json";
import { DBMultiSelect } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBMultiSelect" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName, exampleProps }">
            <DBMultiSelect>{{exampleName}}</DBMultiSelect>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/multi-select/multi-select.component.ts
import { Component } from '@angular/core';

import { DefaultComponent } from '../default.component';
import defaultComponentVariants from '../../../../../shared/multi-select.json';
import { DBMultiSelect } from '../../../../../../output/angular/src/components/multi-select';

@Component({
	selector: 'app-multi-select',
	templateUrl: './multi-select.component.html',
	imports: [DefaultComponent, DBMultiSelect],
	standalone: true
})
export class MultiSelectComponent {
	variants = defaultComponentVariants;
}



<app-default-component
	title="DBMultiSelect"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-multi-select>{{exampleName}}</db-multi-select>
	</ng-template>
</app-default-component>
