// showcases/vue-showcase/src/components/textarea/Textarea.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/textarea.json";
import { DBTextarea } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTextarea" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTextarea
				:cols="exampleProps.cols"
				:disabled="exampleProps.disabled"
				:message="exampleProps.message"
				:required="exampleProps.required"
				:readOnly="exampleProps.readOnly"
				:label="exampleProps.label"
				:labelVariant="exampleProps.labelVariant"
				:placeholder="exampleProps.placeholder || exampleName"
				:rows="exampleProps.rows"
				:value="exampleProps.value"
				:invalid="exampleProps.invalid"
				:variant="exampleProps.variant"
			></DBTextarea>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/textarea/textarea.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/textarea.json';
import { DefaultComponent } from '../default.component';
import { DBTextarea } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-textarea',
	templateUrl: './textarea.component.html',
	imports: [DefaultComponent, DBTextarea],
	standalone: true
})
export class TextareaComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTextarea"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-textarea
			[variant]="exampleProps.variant"
			[labelVariant]="exampleProps.labelVariant"
			[label]="exampleProps.label"
			[required]="exampleProps.required"
			[disabled]="exampleProps.disabled"
			[readOnly]="exampleProps.readOnly"
			[value]="exampleProps.value"
			[cols]="exampleProps.cols"
			[rows]="exampleProps.rows"
			[placeholder]="exampleProps.placeholder || exampleName"
			[message]="exampleProps.message"
			[invalid]="exampleProps.invalid"
		></db-textarea>
	</ng-template>
</app-default-component>
