// showcases/vue-showcase/src/components/infotext/Infotext.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/infotext.json";
import { DBInfotext } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBInfotext" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext
				:size="exampleProps.size"
				:variant="exampleProps.variant"
				:icon="exampleProps.icon"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/infotext/infotext.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/infotext.json';
import { DefaultComponent } from '../default.component';
import { DBInfotext } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-infotext',
	templateUrl: './infotext.component.html',
	imports: [DefaultComponent, DBInfotext],
	standalone: true
})
export class InfotextComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBInfotext"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-infotext
			[size]="exampleProps.size"
			[variant]="exampleProps.variant"
			[icon]="exampleProps.icon"
		>
			{{ exampleName }}
		</db-infotext>
	</ng-template>
</app-default-component>
