// showcases/vue-showcase/src/components/popover/Popover.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/popover.json";
import { DBButton, DBPopover } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBPopover" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBPopover
				:width="exampleProps.width"
				:gap="exampleProps.gap"
				:spacing="exampleProps.spacing"
				:placement="exampleProps.placement"
				:animation="exampleProps.animation"
				:delay="exampleProps.delay"
				:id="exampleProps.id"
			>
				<template v-slot:trigger>
					<DBButton>
						{{ exampleName }}
					</DBButton>
				</template>
				<template v-if="exampleProps.content">{{
					exampleProps.content
				}}</template>
				<template v-if="!exampleProps.content">
					<ul class="popover-list">
						<li>Popover Custom Item 1</li>
						<li>Popover Custom Item 2</li>
					</ul>
					<DBButton>Popover Custom Item 3</DBButton>
				</template>
			</DBPopover>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/popover/index.tsx
import { DBPopover, DBButton } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/popover.json';
import type { DBPopoverProps } from '../../../../../output/react/src/components/popover/model';
import { getVariants } from '../data';

const getPopover = ({
	id,
	children,
	width,
	gap,
	spacing,
	placement,
	delay,
	content,
	animation
}: DBPopoverProps & { content: string }) => (
	<DBPopover
		trigger={<DBButton>{children}</DBButton>}
		width={width}
		gap={gap}
		spacing={spacing}
		placement={placement}
		animation={animation}
		delay={delay}
		id={id}>
		{content ?? (
			<>
				<ul className="popover-list">
					<li>Popover Custom Item 1</li>
					<li>Popover Custom Item 2</li>
				</ul>
				<DBButton>Popover Custom Item 3</DBButton>
			</>
		)}
	</DBPopover>
);

const PopoverComponent = () => {
	return (
		<DefaultComponent
			title="DBPopover"
			variants={getVariants(
				defaultComponentVariants,
				getPopover
			)}></DefaultComponent>
	);
};

export default PopoverComponent;
