// showcases/angular-showcase/src/app/components/tab/tab.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tab.json';
import { DefaultComponent } from '../default.component';
import { DBTab } from '../../../../../../output/angular/src/components/tab';

@Component({
	selector: 'app-tab',
	templateUrl: './tab.component.html',
	imports: [DefaultComponent, DBTab],
	standalone: true
})
export class TabComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTab"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-tab
			[active]="exampleProps.active"
			[noText]="exampleProps.noText"
			[icon]="exampleProps.icon"
			[iconAfter]="exampleProps.iconAfter"
			[width]="exampleProps.width"
			[alignment]="exampleProps.alignment"
			[disabled]="exampleProps.disabled"
		>
			{{ exampleName }}
		</db-tab>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/tab/Tab.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab.json";
import { DBTab } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTab" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTab
				:active="exampleProps.active"
				:noText="exampleProps.noText"
				:icon="exampleProps.icon"
				:iconAfter="exampleProps.iconAfter"
				:width="exampleProps.width"
				:alignment="exampleProps.alignment"
				:disabled="exampleProps.disabled"
			>
				{{ exampleName }}
			</DBTab>
		</template>
	</DefaultComponent>
</template>
