// showcases/react-showcase/src/components/switch/index.tsx
import { DBSwitch, DBInfotext } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/switch.json';
import type { DBSwitchProps } from '../../../../../output/react/src/components/switch/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getSwitch = ({
	children,
	checked,
	visualAid,
	disabled,
	variant,
	emphasis,
	size,
	icon,
	iconAfter
}: DBSwitchProps) => (
	<>
		<DBSwitch
			visualAid={visualAid}
			defaultChecked={checked}
			disabled={disabled}
			variant={variant}
			size={size}
			emphasis={emphasis}
			icon={icon}
			iconAfter={iconAfter}>
			{children}
		</DBSwitch>
		{variant === 'hidden' && (
			<DBInfotext semantic="informational" icon="none">
				{children}
			</DBInfotext>
		)}
	</>
);

const SwitchComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title="DBSwitch"
			variants={getVariants(
				defaultComponentVariants,
				getSwitch,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default SwitchComponent;

// showcases/vue-showcase/src/components/switch/Switch.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/switch.json";
import { DBSwitch, DBInfotext } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBSwitch" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSwitch
				:visualAid="exampleProps.visualAid"
				:checked="exampleProps.checked"
				:disabled="exampleProps.disabled"
				:variant="exampleProps.variant"
				:size="exampleProps.size"
				:emphasis="exampleProps.emphasis"
				:icon="exampleProps.icon"
				:iconAfter="exampleProps.iconAfter"
			>
				{{ exampleName }}
			</DBSwitch>
			<DBInfotext
				v-if="exampleProps.variant === 'hidden'"
				semantic="informational"
				icon="none"
			>
				{{ exampleName }}
			</DBInfotext>
		</template>
	</DefaultComponent>
</template>
