// showcases/vue-showcase/src/components/tab-item/TabItem.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tab-item.json";
import { DBTabItem } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTabItem" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTabItem
				:active="exampleProps.active"
				:noText="exampleProps.noText"
				:icon="exampleProps.icon"
				:iconAfter="exampleProps.iconAfter"
				:disabled="exampleProps.disabled"
			>
				{{ exampleName }}
			</DBTabItem>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/tab-item/tab-item.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tab-item.json';
import { DefaultComponent } from '../default.component';
import { DBTabItem } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-tab',
	templateUrl: './tab-item.component.html',
	imports: [DefaultComponent, DBTabItem],
	standalone: true
})
export class TabItemComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTabItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-tab-item
			[active]="exampleProps.active"
			[noText]="exampleProps.noText"
			[icon]="exampleProps.icon"
			[iconAfter]="exampleProps.iconAfter"
			[disabled]="exampleProps.disabled"
		>
			{{ exampleName }}
		</db-tab-item>
	</ng-template>
</app-default-component>
