// showcases/react-showcase/src/App.tsx
import {
	DBButton,
	DBIcon,
	DBTabBar,
	DBTab
} from "../../../packages/core/output/react/src";

function App() {
	return (
		<main>
			<h1>React</h1>
			<div style={{ display: "flex", gap: "4px", alignItems: "center" }}>
				<DBButton variant="secondary">Test</DBButton>
				<DBButton text="Test" icon="account" />
				<DBIcon icon="account" />
			</div>

			<div
				style={{ display: "flex", gap: "4px", flexDirection: "column" }}
			>
				<h2>TabBar</h2>
				<DBTabBar>
					<DBTab name="tab-bar-1" label="Tab1">
						<strong>Content 1-1</strong>
					</DBTab>
					<DBTab name="tab-bar-1" label="Tab2" active={true}>
						Content 1-2
					</DBTab>
				</DBTabBar>

				<DBTabBar
					tabs={[
						{
							name: "tab-bar-2",
							label: "2-Tab1",
							active: true,
							children: <strong>Content 2-1</strong>
						},
						{
							name: "tab-bar-2",
							label: "2-Tab2",
							content: "Content 2-2"
						}
					]}
				/>
			</div>
		</main>
	);
}

export default App;

// showcases/angular-current-showcase/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html'
})
export class AppComponent {
	title = 'angular-current-showcase';

	tabs = [
		{
			name: 'tab-bar-2',
			label: '2-Tab1',
			active: true,
			children: 'Content 2-1'
		},
		{ name: 'tab-bar-2', label: '2-Tab2', content: 'Content 2-2' }
	];

	onClick() {
		console.log('click button');
	}
}

<main>
	<h1>Angular</h1>
	<DBCard>
		<div style="display: flex; gap: 4px; align-items: center">
			<DBButton variant="secondary">Test</DBButton>
			<DBButton text="Test" icon="account" (click)="onClick()"></DBButton>
			<DBIcon icon="account"></DBIcon>

			<section class="db-ui-expressive">
				<DBInput></DBInput>
			</section>

			<section class="db-ui-regular">
				<DBInput></DBInput>
			</section>

			<section class="db-ui-functional">
				<DBInput></DBInput>
			</section>
		</div>
	</DBCard>
</main>
