// showcases/vue-showcase/src/components/card/Card.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/card.json";
import { DBCard } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBCard" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCard
				:colorVariant="exampleProps.colorVariant"
				:variant="exampleProps.variant"
				:spacing="exampleProps.spacing"
			>
				<strong>{{ exampleName }}</strong>
				<span v-if="exampleProps.colorVariant">{{
					exampleProps.colorVariant
				}}</span>
			</DBCard>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/card/card.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/card.json';
import { DefaultComponent } from '../default.component';
import { DBCard } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-card',
	templateUrl: './card.component.html',
	imports: [DefaultComponent, DBCard],
	standalone: true
})
export class CardComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBCard"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-card
			[colorVariant]="exampleProps.colorVariant"
			[variant]="exampleProps.variant"
			[spacing]="exampleProps.spacing"
		>
			<strong>{{ exampleName }}</strong>
			@if (exampleProps.colorVariant) {
				<span>{{ exampleProps.colorVariant }}</span>
			}
		</db-card>
	</ng-template>
</app-default-component>
