// showcases/vue-showcase/src/components/link/Link.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/link.json";
import { DBLink } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="Link" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName }">
			<template v-if="exampleIndex === 0">
				<DBLink href="#">{{ exampleName }}</DBLink>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 0">
				<DBLink href="#" variant="primary">{{ exampleName }}</DBLink>
			</template>

			<template v-if="exampleIndex === 1 && variantIndex === 1">
				<DBLink href="#" disabled="true">{{ exampleName }}</DBLink>
			</template>

			<template v-if="exampleIndex === 1 && variantIndex === 2">
				<DBLink href="#" size="small">{{ exampleName }}</DBLink>
			</template>

			<template v-if="exampleIndex === 1 && variantIndex === 3">
				<DBLink href="#" content="external">{{ exampleName }}</DBLink>
			</template>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/link/index.tsx
import { DBLink } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import { type DefaultComponentExample } from '../../../../shared/default-component-data';
import defaultComponentVariants from '../../../../shared/link.json';
import { type DBLinkProps } from '../../../../../output/react/src/components/link/model';
import { getVariants } from '../data';

const getLink = ({
	variant,
	disabled,
	size,
	content,
	children
}: DBLinkProps) => (
	<DBLink
		href="#"
		variant={variant}
		disabled={disabled}
		size={size}
		content={content}>
		{children}
	</DBLink>
);

const getExampleMatrix = (exampleName: string): DefaultComponentExample[][] => [
	[
		{
			example: getLink({ children: exampleName })
		},
		{
			example: getLink({ children: exampleName, variant: 'primary' })
		}
	],
	[
		{
			example: getLink({ children: exampleName })
		},
		{
			example: getLink({ children: exampleName, disabled: true })
		}
	],
	[
		{
			example: getLink({ children: exampleName })
		},
		{
			example: getLink({ children: exampleName, size: 'small' })
		}
	],
	[
		{
			example: getLink({ children: exampleName })
		},
		{
			example: getLink({ children: exampleName, content: 'external' })
		}
	]
];

const LinkComponent = () => {
	return (
		<DefaultComponent
			title={'DBLink'}
			variants={getVariants(
				defaultComponentVariants,
				getExampleMatrix
			)}></DefaultComponent>
	);
};

export default LinkComponent;
