// showcases/angular-showcase/src/app/components/select/select.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/select.json';
import { DefaultComponent } from '../default.component';
import { DBSelect } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-select',
	templateUrl: './select.component.html',
	imports: [DefaultComponent, DBSelect],
	standalone: true
})
export class SelectComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBSelect"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-select
			[label]="exampleProps?.label"
			[placeholder]="exampleName"
			[variant]="exampleProps?.variant"
			[showLabel]="exampleProps?.showLabel"
			[options]="exampleProps?.options"
			[disabled]="exampleProps?.disabled"
			[icon]="exampleProps?.icon"
			[required]="exampleProps?.required"
			[value]="exampleProps?.value"
			[message]="exampleProps?.message"
			>{{ exampleName }}</db-select
		>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/select/Select.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/select.json";
import { DBCheckbox, DBSelect } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBSelect" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSelect
				:label="exampleProps?.label"
				:placeholder="exampleName"
				:variant="exampleProps?.variant"
				:show-label="exampleProps?.showLabel"
				:options="exampleProps?.options"
				:disabled="exampleProps?.disabled"
				:icon="exampleProps?.icon"
				:value="exampleProps?.value"
				:message="exampleProps?.message"
				:required="exampleProps?.required"
			>
				{{ exampleName }}
			</DBSelect>
		</template>
	</DefaultComponent>
</template>
