// showcases/angular-showcase/src/app/components/tooltip/tooltip.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tooltip.json';
import { DefaultComponent } from '../default.component';
import { DBButton, DBTooltip } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-tooltip',
	templateUrl: './tooltip.component.html',
	imports: [DefaultComponent, DBTooltip, DBButton],
	standalone: true
})
export class TooltipComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTooltip"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-button [describedbyid]="exampleProps.id">
			{{ exampleName }}
			<db-tooltip
				[width]="exampleProps.width"
				[emphasis]="exampleProps.emphasis"
				[placement]="exampleProps.placement"
				[animation]="exampleProps.animation"
				[delay]="exampleProps.delay"
				[variant]="exampleProps.variant"
				[id]="exampleProps.id"
				>{{ exampleProps.content }}</db-tooltip
			>
		</db-button>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/tooltip/Tooltip.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tooltip.json";
import { DBButton, DBTooltip } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTooltip" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBButton :describedbyid="exampleProps.id">
				{{ exampleName }}
				<DBTooltip
					:width="exampleProps.width"
					:emphasis="exampleProps.emphasis"
					:placement="exampleProps.placement"
					:animation="exampleProps.animation"
					:delay="exampleProps.delay"
					:variant="exampleProps.variant"
					:id="exampleProps.id"
				>
					{{ exampleProps.content }}
				</DBTooltip>
			</DBButton>
		</template>
	</DefaultComponent>
</template>
