// showcases/angular-showcase/src/app/components/form/form.component.ts
import { Component } from '@angular/core';

@Component({
	selector: 'app-form',
	templateUrl: './form.component.html'
})
export class FormComponent {
	input = '';
	radioNames = ['X', 'Y', 'Z'];
	radio = '';

	dataList = [{ key: 'test', value: 'Test' }, { key: 'test2' }];
	getRadioName = (radioName: string): string => `Radio ${radioName}`;
	showValues(): void {
		// eslint-disable-next-line no-alert
		alert(
			JSON.stringify({
				input: this.input,
				radio: this.radio
			})
		);
	}
}

<div class="form-container">
	<div>
		<form [formGroup]="form" (submit)="onFormSubmit()">
			<fieldset>
				<p>Input:</p>
				<!-- OR [(ngModel)]="model.input" -->
				<db-input
					name="form"
					id="form"
					label="Textinput"
					placeholder="Placeholder"
					description="Description"
					icon="account"
					formControlName="input"
				>
				</db-input>

				<db-input
					name="form"
					id="datalist"
					label="Textinput with Datalist"
					placeholder="Placeholder"
					description="Description"
					[dataList]="dataList"
					icon="account"
				>
				</db-input>

				<p>Radio:</p>
				<ul>
					<li *ngFor="let radioName of radioNames">
						<db-radio
							label="Label"
							name="RadioGroup"
							[value]="radioName"
							(change)="model.radio = radioName"
							[label]="getRadioName(radioName)"
						></db-radio>
					</li>
				</ul>
				<p>Checkbox:</p>
				<db-checkbox
					(change)="model.checkbox = $event.target.checked"
					name="checkbox"
					label="Checkbox"
				></db-checkbox>
				<p>DBSelect:</p>
				<db-select
					[value]="select"
					label="Label"
					(change)="select = $event.target.value"
				>
					<option value="test1">Test1</option>
					<option value="test2">Test2</option>
				</db-select>
				<p>Button:</p>
				<db-button type="button" (click)="resetValues()">
					Reset
				</db-button>
				<db-button type="submit" variant="primary">
					Hi from Showcase!
				</db-button>
			</fieldset>
		</form>
	</div>
	<div>
		<h2>Output</h2>
		<dl>
			<dt>inputs value</dt>
			<dd>
				{{
					form.get("input")?.value
						? form.get("input")?.value
						: "No Input set"
				}}
			</dd>
			<dt>radio value</dt>
			<dd>{{ model.radio ? model.radio : "No radio set" }}</dd>
			<dt>checkbox value</dt>
			<dd>checkbox {{ checkbox ? "" : "un" }}checked</dd>
			<dt>select value</dt>
			<dd>{{ select ? select : "No select set" }}</dd>
		</dl>
	</div>
</div>

// showcases/vue-showcase/src/components/form/Form.vue
<script setup lang="ts">
import {
	DBButton,
	DBInput,
	DBRadio,
	DBCheckbox,
	DBSelect
} from "../../../../../output/vue/vue3/src";

import { ref } from "vue";
const input = ref("");
const radio = ref("");
const checkbox = ref("");
const select = ref("");

const radioNames = ["X", "Y", "Z"];

const dataList = [{ key: "test", value: "Test" }, { key: "test2" }];

// eslint-disable-next-line no-alert
const logAll = () => {
	alert(
		JSON.stringify({
			input: input.value,
			radio: radio.value,
			select: select.value,
			checkbox: checkbox.checked
		})
	);
};
</script>

<template>
	<div class="form-container">
		<div>
			<form>
				<fieldset>
					<p>Input:</p>
					<DBInput
						label="Textinput"
						placeholder="Placeholder"
						description="Description"
						icon="account"
						name="input-name"
						class="fullWidth"
						:dataList="dataList"
						v-model:value="input"
					/>
					<p>Radio:</p>
					<ul>
						<li v-for="radioName in radioNames">
							<DBRadio
								@change="radio = radioName"
								name="radio-group"
								:value="radioName"
								>Radio {{ radioName }}</DBRadio
							>
						</li>
					</ul>
					<p>Checkbox:</p>
					<DBCheckbox
						@change="checkbox = $event.target.checked"
						name="checkbox"
						>Checkbox</DBCheckbox
					>
					<p>DBSelect:</p>
					<DBSelect
						:value="select"
						label="Label"
						@change="(event) => (select = event.target.value)"
					>
						<option value="test1">Test1</option>
						<option value="test2">Test2</option>
					</DBSelect>
					<p>Button:</p>
					<DBButton type="button" variant="primary" @click="logAll()">
						Hi from Showcase!
					</DBButton>
				</fieldset>
			</form>
		</div>
		<div>
			<h2>Output</h2>
			<dl>
				<dt>inputs value</dt>
				<dd>{{ input ? input : "No Input set" }}</dd>
				<dt>radio value</dt>
				<dd>{{ radio ? radio : "No radio set" }}</dd>
				<dt>checkbox value</dt>
				<dd>{{ `checkbox ${checkbox ? "" : "un"}checked` }}</dd>
				<dt>select value</dt>
				<dd>{{ select ? select : "No select set" }}</dd>
			</dl>
		</div>
	</div>
</template>
