// showcases/angular-showcase/src/app/components/default.component.ts
import {
	Component,
	OnInit,
	Input,
	TemplateRef,
	NO_ERRORS_SCHEMA
} from '@angular/core';
import { NgTemplateOutlet } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { DBLink } from '../../../../../output/angular/src/components/link/link';
import { DBDivider } from '../../../../../output/angular/src/components/divider/divider';
import { DBCodeDocs } from '../../../../../output/angular/src/components/code-docs/code-docs';
import type {
	DefaultComponentProps,
	DefaultComponentVariants,
	DefaultComponentExample
} from '../../../../shared/default-component-data';
import {
	COLOR,
	COLOR_CONST,
	TONALITY,
	TONALITY_CONST
} from '../../../../../packages/components/src/shared/constants';

@Component({
	selector: 'app-default-component',
	templateUrl: './default.component.html',
	imports: [DBCodeDocs, DBDivider, DBLink, NgTemplateOutlet],
	standalone: true,
	schemas: [NO_ERRORS_SCHEMA]
})
export class DefaultComponent implements OnInit {
	@Input() title: DefaultComponentProps['title'] = '';
	@Input() variants: DefaultComponentProps['variants'] = [];
	@Input() exampleTemplate!: TemplateRef<any>;

	tonality = TONALITY.REGULAR;
	color = COLOR.NEUTRAL;
	page?: string;

	variantRef: DefaultComponentVariants | undefined;
	variantRefIndex = 0;

	constructor(private readonly route: ActivatedRoute) {}

	ngOnInit(): void {
		this.route.queryParams.subscribe((parameters) => {
			if (parameters[TONALITY_CONST]) {
				this.tonality = parameters[TONALITY_CONST];
			}

			if (parameters['page']) {
				this.page = parameters['page'];

				const foundVariant = this.variants.find(
					(variant) => variant.name.toLowerCase() === this.page
				);

				this.variantRef = foundVariant;
				if (foundVariant) {
					this.variantRefIndex = this.variants.indexOf(foundVariant);
				}
			}

			if (parameters[COLOR_CONST]) {
				this.color = parameters[COLOR_CONST];
			}
		});
	}

	getLink = (variantName: string) => {
		let currentUrl = window.location.href;
		if (!currentUrl.includes('?')) {
			currentUrl += '?';
		}

		if (!currentUrl.includes('color=')) {
			currentUrl += `&color=${this.color || COLOR.NEUTRAL}`;
		}

		if (!currentUrl.includes('tonality=')) {
			currentUrl += `&tonality=${this.tonality || TONALITY.REGULAR}`;
		}

		return `${currentUrl}&page=${variantName.toLowerCase()}`;
	};

	getCodeSnippets = (examples: DefaultComponentExample[]) => {
		return examples
			.filter((example) => example.code)
			.map((example) => `/* ${example.name} */\n${example.code}`);
	};
}

<!-- TODO: Content Projection not working for nested components? -> Had to copy paste variant-cards... -->
@if (variantRef) {
	<db-card class="variants-card" [elevationLevel]="getElevation()">
		<div
			class="variants-list"
			[attr.aria-label]="variantRef.role ? variantRef.name : undefined"
			[attr.role]="variantRef.role"
		>
			@for (
				example of variantRef.examples;
				track example;
				let exampleIndex = $index
			) {
				<div
					[style]="example.style"
					[class]="example.className"
					[attr.data-density]="example.density"
				>
					<ng-container
						*ngTemplateOutlet="
							exampleTemplate;
							context: {
								exampleProps: example.props ?? {},
								exampleName: example.name,
								exampleIndex: exampleIndex,
								variantIndex: variantRefIndex
							}
						"
					>
					</ng-container>
				</div>
			}
		</div>
	</db-card>
}

@if (!variantRef) {
	<div class="default-container">
		<h1>{{ title }}</h1>
		@for (variant of variants; track variant; let variantIndex = $index) {
			<div>
				<db-divider></db-divider>
				<db-link
					class="link-headline"
					content="external"
					target="_blank"
					[href]="getLink(variant.name)"
				>
					<span>{{ variant.name }}</span>
				</db-link>
				<db-card
					class="variants-card"
					[elevationLevel]="getElevation()"
				>
					<div
						class="variants-list"
						[attr.aria-label]="
							variant.role ? variant.name : undefined
						"
						[attr.role]="variant.role"
					>
						@for (
							example of variant.examples;
							track example;
							let exampleIndex = $index
						) {
							<div
								[style]="example.style"
								[class]="example.className"
								[attr.data-density]="example.density"
							>
								<ng-container
									*ngTemplateOutlet="
										exampleTemplate;
										context: {
											exampleProps: example.props,
											exampleName: example.name,
											exampleIndex: exampleIndex,
											variantIndex: variantIndex
										}
									"
								>
								</ng-container>
							</div>
						}
					</div>
				</db-card>
			</div>
		}
	</div>
}

// showcases/react-showcase/src/components/default-component.tsx
import React, { useCallback, useState } from 'react';
import { DBCard, DBDivider, DBLink } from '../../../../output/react/src';
import useQuery from '../hooks/use-query';
import type {
	DefaultComponentProps,
	DefaultComponentVariants
} from '../../../shared/default-component-data';
import useUniversalSearchParameters from '../hooks/use-universal-search-parameters';

const VariantList = ({
	examples,
	color,
	SlotCode
}: DefaultComponentVariants) => {
	const getElevation = useCallback(
		() => (color?.includes('3') ? '3' : color?.includes('2') ? '2' : '1'),
		[color]
	);

	const [open, setOpen] = useState<boolean>();

	return (
		<DBCard
			className="variants-card db-code-docs"
			elevationLevel={getElevation()}>
			<div className="variants-list">
				{examples.map((example, exampleIndex) => (
					<div
						key={`${example.name}-${exampleIndex}`}
						style={example.style}
						className={example.className}>
						{example.example}
					</div>
				))}
			</div>

			{SlotCode && (
				<details
					className="code-details"
					onToggle={() => {
						setOpen(!open);
					}}>
					<summary
						className="db-button code-button"
						data-size="small"
						data-variant="filled">
						{open ? 'Hide code' : 'Show code'}
					</summary>
					<div className="db-density-functional">
						<div className="backdrop" />
						<DBCard className="code" spacing="small">
							<SlotCode />
						</DBCard>
					</div>
				</details>
			)}
		</DBCard>
	);
};

const DefaultComponent = ({
	title,
	variants,
	subComponent,
	isSubComponent,
	componentName
}: DefaultComponentProps) => {
	const pageName = useQuery()[4];
	const color = useQuery()[2];

	const getHref = (variantName: string): string => {
		if (typeof window !== 'undefined') {
			return `${window.location.href}&page=${variantName.toLowerCase()}`;
		}

		return '';
	};

	const openVariantInNewWindow = (
		event: React.MouseEvent<HTMLAnchorElement>,
		variantName: string
	) => {
		if (
			typeof window === 'undefined' ||
			!window.location.origin ||
			!window.location.href
		) {
			return;
		}

		const currentUrl = window.location.href.split('?');
		const searchParams = new URLSearchParams(currentUrl[1] ?? '');
		searchParams.set('page', variantName.toLowerCase());

		const rawComponentUrl = currentUrl[0].replace('/overview', '');

		const openUrl = componentName
			? `${rawComponentUrl.split('components')[0]}/components/${componentName}?${searchParams.toString()}`
			: `${rawComponentUrl}?${searchParams.toString()}`;

		window.open(openUrl, '_blank');
	};

	if (pageName) {
		const foundVariant = variants.find(
			(variant) => variant.name.toLowerCase() === pageName
		);
		if (foundVariant) {
			return <VariantList {...foundVariant} color={color} />;
		}
	}

	const HeadlineTag = isSubComponent ? 'h2' : 'h1';

	return (
		<>
			<div className="default-container">
				<HeadlineTag>{title}</HeadlineTag>
				{variants?.map((variant, index) => (
					<div key={`${variant.name}-${index}`}>
						<DBDivider></DBDivider>
						<DBLink
							className="link-headline"
							content="external"
							target="_blank"
							onClick={(event) => {
								openVariantInNewWindow(event, variant.name);
							}}
							href={getHref(variant.name)}>
							{variant.name}
						</DBLink>
						<VariantList {...variant} color={color} />
					</div>
				))}
			</div>
			{subComponent}
		</>
	);
};

export default DefaultComponent;
