// showcases/angular-showcase/src/app/components/alert/alert.component.ts
import { Component } from '@angular/core';
import { DBAlert } from '../../../../../../output/angular/src/components/alert/alert';
import defaultComponentVariants from '../../../../../shared/alert.json';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-alert',
	templateUrl: './alert.component.html',
	imports: [DefaultComponent, DBAlert],
	standalone: true
})
export class AlertComponent {
	variants = defaultComponentVariants;

	showAlert = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<app-default-component
	title="DBAlert"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-alert
			[variant]="exampleProps.variant"
			[headline]="exampleProps.headline"
			[link]="exampleProps.link"
			[icon]="exampleProps.icon"
			[behaviour]="exampleProps.behaviour"
			[type]="exampleProps.type"
			(click)="showAlert(exampleName)"
		>
			{{ exampleName }}
			<span *ngIf="exampleProps.slotLink" #link>{{
				exampleProps.slotLink
			}}</span>
		</db-alert>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/alert/Alert.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/alert.json";
import { DBAlert } from "../../../../../output/vue/vue3/src";

const log = (exampleName: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent title="Alert" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBAlert
				:variant="exampleProps.variant"
				:headline="exampleProps.headline"
				:link="exampleProps.link"
				:icon="exampleProps.icon"
				:behaviour="exampleProps.behaviour"
				:type="exampleProps.type"
				@click="log(exampleName)"
			>
				{{ exampleName }}
				<span v-if="exampleProps.slotLink" slot="link">{{
					exampleProps.slotLink
				}}</span>
			</DBAlert>
		</template>
	</DefaultComponent>
</template>
