// showcases/react-showcase/src/components/alert/index.tsx
import { DBAlert } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/alert.json';
import { type DBAlertProps } from '../../../../../output/react/src/components/alert/model';
import { getVariants } from '../data';

const getAlert = ({
	variant,
	icon,
	headline,
	link,
	type,
	children,
	behaviour
}: DBAlertProps) => (
	<DBAlert
		variant={variant}
		icon={icon}
		headline={headline}
		link={link}
		type={type}
		behaviour={behaviour}
		onClick={() => {
			// eslint-disable-next-line no-alert
			alert(children.toString());
		}}>
		{children}
	</DBAlert>
);

const AlertComponent = () => {
	return (
		<DefaultComponent
			title="DBAlert"
			variants={getVariants(
				defaultComponentVariants,
				getAlert
			)}></DefaultComponent>
	);
};

export default AlertComponent;

// showcases/vue-showcase/src/components/alert/Alert.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/alert.json";
import { DBAlert } from "../../../../../output/vue/vue3/src";

const log = (exampleName: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent title="DBAlert" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBAlert
				:variant="exampleProps.variant"
				:headline="exampleProps.headline"
				:link="exampleProps.link"
				:icon="exampleProps.icon"
				:behaviour="exampleProps.behaviour"
				:type="exampleProps.type"
				@click="log(exampleName)"
			>
				{{ exampleName }}
			</DBAlert>
		</template>
	</DefaultComponent>
</template>
