// showcases/react-showcase/src/components/navigation-item/index.tsx
import { DBNavigationItem, DBButton } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/navigation-item.json';
import type { DBNavigationItemProps } from '../../../../../output/react/src/components/navigation-item/model';
import { getVariants } from '../data';

const getNavigationItem = ({
	children,
	icon,
	disabled,
	active,
	width,
	areaPopup
}: DBNavigationItemProps) => (
	<DBNavigationItem
		icon={icon}
		disabled={disabled}
		active={active}
		width={width}
		areaPopup={areaPopup}
		onClick={() => {
			// eslint-disable-next-line no-alert
			alert(children.toString());
		}}
		slotSubNavigation={
			areaPopup && (
				<>
					<DBNavigationItem>
						<a href="#">Test1</a>
					</DBNavigationItem>
					<DBNavigationItem>
						<a href="#">Test2</a>
					</DBNavigationItem>
				</>
			)
		}>
		{areaPopup ? children : <a href="#">{children}</a>}
	</DBNavigationItem>
);

const NavigationItemComponent = () => {
	return (
		<DefaultComponent
			title="DBNavigationItem"
			variants={getVariants(
				defaultComponentVariants,
				getNavigationItem
			)}></DefaultComponent>
	);
};

export default NavigationItemComponent;

// showcases/vue-showcase/src/components/navigation-item/NavigationItem.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/navigation-item.json";
import { DBNavigationItem } from "../../../../../output/vue/src";

const log = (exampleName?: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent
		title="DBNavigationItem"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBNavigationItem
				:icon="exampleProps.icon"
				:width="exampleProps.width"
				:disabled="exampleProps.disabled"
				:active="exampleProps.active"
				:areaPopup="exampleProps.areaPopup"
				@click="log(exampleName)"
			>
				<template v-if="exampleProps.areaPopup" #sub-navigation>
					<DBNavigationItem><a href="#">Test1</a></DBNavigationItem>
					<DBNavigationItem><a href="#">Test2</a></DBNavigationItem>
					<DBNavigationItem><a href="#">Test3</a></DBNavigationItem>
				</template>
				<template v-if="exampleProps.areaPopup">
					{{ exampleName }}
				</template>
				<a v-if="!exampleProps.areaPopup" href="#">{{ exampleName }}</a>
			</DBNavigationItem>
		</template>
	</DefaultComponent>
</template>
