// showcases/angular-showcase/src/app/components/navigation-item/navigation-item.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/navigation-item.json';
import { DefaultComponent } from '../default.component';
import {
	DBNavigationItem,
	NavigationContentDirective
} from '../../../../../../output/angular/src';

@Component({
	selector: 'app-navigation-item',
	templateUrl: './navigation-item.component.html',
	imports: [DefaultComponent, DBNavigationItem, NavigationContentDirective],
	standalone: true
})
export class NavigationItemComponent {
	variants = defaultComponentVariants;

	showAlert = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<app-default-component
	title="DBNavigationItem"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<ul>
			<db-navigation-item
				[icon]="exampleProps.icon"
				[width]="exampleProps.width"
				[disabled]="exampleProps.disabled"
				[active]="exampleProps.active"
				[areaPopup]="exampleProps.areaPopup"
				(click)="showAlert(exampleName)"
			>
				<ng-container *dbNavigationContent>
					@if (exampleProps.areaPopup) {
						{{ exampleName }}
					}
					@if (!exampleProps.areaPopup) {
						<a href="#">{{ exampleName }}</a>
					}
				</ng-container>

				@if (exampleProps.areaPopup) {
					<ng-container sub-navigation>
						<ul>
							<db-navigation-item [areaPopup]="false">
								<ng-container *dbNavigationContent>
									<a href="#">Test1</a>
								</ng-container>
							</db-navigation-item>
							<db-navigation-item [areaPopup]="false">
								<ng-container *dbNavigationContent>
									<a href="#">Test2</a>
								</ng-container>
							</db-navigation-item>
							<db-navigation-item [areaPopup]="false">
								<ng-container *dbNavigationContent>
									<a href="#">Test3</a>
								</ng-container>
							</db-navigation-item>
						</ul>
					</ng-container>
				}
			</db-navigation-item>
		</ul>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/navigation-item/NavigationItem.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/navigation-item.json";
import { DBNavigationItem } from "../../../../../output/vue/src";

const log = (exampleName?: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent
		title="DBNavigationItem"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBNavigationItem
				:icon="exampleProps.icon"
				:width="exampleProps.width"
				:disabled="exampleProps.disabled"
				:active="exampleProps.active"
				:areaPopup="exampleProps.areaPopup"
				@click="log(exampleName)"
			>
				<template v-if="exampleProps.areaPopup" #sub-navigation>
					<DBNavigationItem><a href="#">Test1</a></DBNavigationItem>
					<DBNavigationItem><a href="#">Test2</a></DBNavigationItem>
					<DBNavigationItem><a href="#">Test3</a></DBNavigationItem>
				</template>
				<template v-if="exampleProps.areaPopup">
					{{ exampleName }}
				</template>
				<a v-if="!exampleProps.areaPopup" href="#">{{ exampleName }}</a>
			</DBNavigationItem>
		</template>
	</DefaultComponent>
</template>
