// showcases/angular-showcase/src/app/components/accordion/accordion.component.ts
import { Component } from '@angular/core';
import {
	DBAccordion,
	DBAccordionItem,
	DBInfotext
} from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/accordion.json';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-accordion',
	templateUrl: './accordion.component.html',
	imports: [DefaultComponent, DBInfotext, DBAccordion, DBAccordionItem],
	standalone: true
})
export class AccordionComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBAccordion"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
		><ng-container>
			<db-infotext size="small" semantic="informational" icon="none">
				{{ exampleName }}
			</db-infotext>
			<db-accordion
				[behaviour]="exampleProps.behaviour"
				[variant]="exampleProps.variant"
			>
				<db-accordion-item
					headlinePlain="Item 1"
					content="Content 1"
				></db-accordion-item>
				<db-accordion-item
					headlinePlain="Item 2"
					content="Content 2"
				></db-accordion-item>
				<db-accordion-item
					headlinePlain="Item 3"
					content="Content 3"
				></db-accordion-item>
			</db-accordion>
		</ng-container>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/accordion/Accordion.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/accordion.json";
import {
	DBAccordion,
	DBAccordionItem,
	DBInfotext
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBAccordion" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext size="small" semantic="informational" icon="none">
				{{ exampleName }}
			</DBInfotext>
			<DBAccordion
				:behaviour="exampleProps.behaviour"
				:variant="exampleProps.variant"
			>
				<DBAccordionItem headlinePlain="Item 1" content="Content 1" />
				<DBAccordionItem headlinePlain="Item 2" content="Content 2" />
				<DBAccordionItem headlinePlain="Item 3" content="Content 3" />
			</DBAccordion>
		</template>
	</DefaultComponent>
</template>
