// showcases/vue-showcase/src/components/header/Header.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/header.json";
import {
	DBBrand,
	DBButton,
	DBHeader,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBHeader" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBHeader
				:width="exampleProps.width"
				:force-mobile="exampleProps.forceMobile"
			>
				<template v-slot:brand>
					<DBBrand>
						<template
							v-if="
								!exampleProps.example || exampleProps.withName
							"
						>
							DBHeader
						</template>
					</DBBrand>
				</template>
				<template
					v-if="!exampleProps.example || exampleProps.withNavigation"
				>
					<DBNavigation :aria-label="exampleName">
						<DBNavigationItem icon="user">
							<a href="#">{{ exampleName }}</a>
						</DBNavigationItem>
						<DBNavigationItem :disabled="true">
							<a href="#">{{ exampleName }} disabled</a>
						</DBNavigationItem>
					</DBNavigation>
				</template>
				<template v-slot:primary-action>
					<template v-if="!exampleProps.example">
						<DBButton
							icon="magnifying_glass"
							variant="ghost"
							:no-text="true"
						>
							Search
						</DBButton></template
					>
				</template>
				<template v-slot:secondary-action>
					<template v-if="!exampleProps.example">
						<DBButton icon="user" variant="ghost" :no-text="true">
							Profile
						</DBButton>
						<DBButton icon="bell" variant="ghost" :no-text="true">
							Notification
						</DBButton>
						<DBButton
							icon="question_mark_circle"
							variant="ghost"
							:no-text="true"
						>
							Help
						</DBButton></template
					>
				</template>
				<template v-slot:meta-navigation>
					<template v-if="!exampleProps.example">
						<DBLink href="#">Imprint</DBLink>
						<DBLink href="#">Help</DBLink></template
					>
				</template>
			</DBHeader>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/header/index.tsx
import {
	DBBrand,
	DBButton,
	DBHeader,
	DBLink,
	DBNavigation,
	DBNavigationItem
} from '../../../../../output/react/src';
import { type DBHeaderProps } from '../../../../../output/react/src/components/header/model';
import defaultComponentVariants from '../../../../shared/header.json';
import { getVariants } from '../data';
import DefaultComponent from '../index';

const getHeader = ({
	drawerOpen,
	forceMobile,
	burgerMenuLabel,
	children,
	className,
	describedbyid,
	id,
	key,
	onToggle,
	width,
	example,
	withNavigation,
	withName
}: DBHeaderProps & {
	example: boolean;
	withName: boolean;
	withNavigation: boolean;
}) => (
	<DBHeader
		width={width}
		brand={
			<DBBrand title="DBHeader">
				{(!example || withName) && 'DBHeader'}
			</DBBrand>
		}
		metaNavigation={
			!example && (
				<>
					<DBLink href="#">Imprint</DBLink>
					<DBLink href="#">Help</DBLink>
				</>
			)
		}
		primaryAction={
			!example && (
				<DBButton icon="magnifying_glass" variant="ghost" noText>
					Search
				</DBButton>
			)
		}
		secondaryAction={
			!example && (
				<>
					<DBButton icon="user" variant="ghost" noText>
						Profile
					</DBButton>
					<DBButton icon="bell" variant="ghost" noText>
						Notification
					</DBButton>
					<DBButton
						icon="question_mark_circle"
						variant="ghost"
						noText>
						Help
					</DBButton>
				</>
			)
		}
		drawerOpen={drawerOpen}
		forceMobile={forceMobile}
		burgerMenuLabel={burgerMenuLabel}
		className={className}
		describedbyid={describedbyid}
		id={id}
		key={key}
		onToggle={onToggle}>
		{(!example || withNavigation) && (
			<DBNavigation aria-label={children}>
				<DBNavigationItem icon="user">
					<a href="#">{children}</a>
				</DBNavigationItem>
				<DBNavigationItem disabled>
					<a href="#">{children} disabled</a>
				</DBNavigationItem>
			</DBNavigation>
		)}
	</DBHeader>
);

const HeaderComponent = () => {
	return (
		<DefaultComponent
			title="DBHeader"
			variants={getVariants(
				defaultComponentVariants,
				getHeader
			)}></DefaultComponent>
	);
};

export default HeaderComponent;
