// showcases/svelte-showcase/src/App.svelte
<script>
	import DBButton from "../../../packages/core/output/svelte/src/components/button/button.svelte";
	import DBIcon from "../../../packages/core/output/svelte/src/components/icon/icon.svelte";
</script>

<main>
	<h1>Svelte</h1>
	<div style="display: flex; gap: 4px; align-items: center">
		<DBButton variant="secondary">Test</DBButton>
		<DBButton text="Test" icon="account" />
		<DBIcon icon="account" />
	</div>
</main>

// showcases/preact-showcase/src/app.jsx
import { DBButton, DBIcon } from "../../../packages/core/output/preact/src";

export function App() {
  return (
    <main>
      <h1>Preact</h1>
      <div>
        <DBButton variant="secondary">Test</DBButton>
        <DBButton text="Test" icon="account" />
        <DBIcon icon="account" />
      </div>
    </main>
  );
}
