// showcases/react-showcase/src/navigation/nav-item.tsx
import { Link, useLocation } from 'react-router-dom';
import { DBNavigationItem } from '../../../../output/react/src';
import type { NavigationItem } from '../utils/navigation-item';

const NavItem = ({ navItem }: { navItem: NavigationItem }) => {
	const location = useLocation();

	const isActive =
		navItem.path === ''
			? location.pathname === '/'
			: location.pathname.includes(navItem.path);

	return (
		<DBNavigationItem
			active={isActive}
			backButtonText={`Back to ${navItem.label}`}
			slotSubNavigation={
				navItem.subNavigation && (
					<>
						{navItem.subNavigation
							.map((subItem: NavigationItem) => ({
								...subItem,
								path: `${navItem.path}/${subItem.path}`
							}))
							.map((subItem: NavigationItem) => (
								<NavItem
									key={`router-path-${subItem.path}`}
									navItem={subItem}></NavItem>
							))}
					</>
				)
			}>
			{navItem.component ? (
				<Link key={`router-path-${navItem.path}`} to={navItem.path}>
					{navItem.label}
				</Link>
			) : (
				navItem.label
			)}
		</DBNavigationItem>
	);
};

export default NavItem;

// showcases/vue-showcase/src/NavItemComponent.vue
<script setup lang="ts">
import { DBNavigationItem } from "../../../output/vue/src";
import { NavItem } from "./utils/navigation-items";
import { useRoute } from "vue-router";

defineProps<{
	navItem: NavItem;
}>();

const route = useRoute();

const isActive = (navItem: NavItem) =>
	navItem.path !== "/"
		? route.path.includes(navItem.path)
		: route.path === "/";
</script>

<template>
	<DBNavigationItem
		:backButtonText="`Back to ${navItem.label}`"
		:active="isActive(navItem)"
	>
		<template v-if="navItem.subNavigation" v-slot:subnavigation>
			<template v-for="item of navItem.subNavigation">
				<NavItemComponent :navItem="item"></NavItemComponent>
			</template>
		</template>
		<router-link v-if="navItem.component" :to="navItem.path">
			{{ navItem.label }}
		</router-link>
		<template v-if="!navItem.component">{{ navItem.label }}</template>
	</DBNavigationItem>
</template>
