// showcases/angular-showcase/src/app/components/main-navigation/main-navigation.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/main-navigation.json';
import { DefaultComponent } from '../default.component';
import { DBMainNavigation } from '../../../../../../output/angular/src/components/main-navigation/main-navigation';
import { DBNavigationItem } from '../../../../../../output/angular/src/components/navigation-item/navigation-item';
import { NavigationContentDirective } from '../../../../../../output/angular/src/components/navigation-item/NavigationContent.directive';

@Component({
	selector: 'app-main-navigation',
	templateUrl: './main-navigation.component.html',
	imports: [
		DefaultComponent,
		DBMainNavigation,
		DBNavigationItem,
		NavigationContentDirective
	],
	standalone: true
})
export class MainNavigationComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="db-main-navigation"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<div>
			<h6>{{ exampleName }}</h6>
			<db-main-navigation>
				<db-navigation-item [active]="true">
					<ng-container *dbNavigationContent>
						Navi-Item 1
					</ng-container>
					<ng-container sub-navigation>
						<db-navigation-item [active]="true">
							<ng-container *dbNavigationContent>
								Sub-Navi-Item 1
							</ng-container>
							<ng-container sub-navigation>
								<db-navigation-item
									[active]="true"
									[areaPopup]="false"
								>
									<ng-container *dbNavigationContent>
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</ng-container>
								</db-navigation-item>
								<db-navigation-item [areaPopup]="false">
									<ng-container *dbNavigationContent>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</ng-container>
								</db-navigation-item>
							</ng-container>
						</db-navigation-item>
						<db-navigation-item [areaPopup]="false">
							<ng-container *dbNavigationContent>
								<a href="#">Sub-Navi-Item 2</a>
							</ng-container>
						</db-navigation-item>
					</ng-container>
				</db-navigation-item>
				<db-navigation-item icon="account" [areaPopup]="false">
					<ng-container *dbNavigationContent>
						<a href="#">Navi-Item 2</a>
					</ng-container>
				</db-navigation-item>
				<db-navigation-item [disabled]="true" [areaPopup]="false">
					<ng-container *dbNavigationContent>
						<a href="#">Navi-Item 3</a>
					</ng-container>
				</db-navigation-item>
			</db-main-navigation>
		</div>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/main-navigation/MainNavigation.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/main-navigation.json";
import {
	DBMainNavigation,
	DBNavigationItem
} from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent
		title="DBMainNavigation"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<div>
				<h6>{{ exampleName }}</h6>
				<DBMainNavigation>
					<DBNavigationItem :active="true">
						Navi-Item 1
						<template v-slot:sub-navigation>
							<DBNavigationItem :active="true">
								Sub-Navi-Item 1

								<template v-slot:sub-navigation>
									<DBNavigationItem :active="true">
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</DBNavigationItem>
									<DBNavigationItem>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</DBNavigationItem>
								</template>
							</DBNavigationItem>
							<DBNavigationItem>
								<a href="#">Sub-Navi-Item 2</a>
							</DBNavigationItem>
						</template>
					</DBNavigationItem>
					<DBNavigationItem icon="account">
						<a href="#">Navi-Item 2</a>
					</DBNavigationItem>
					<DBNavigationItem :disabled="true">
						<a href="#">Navi-Item 3</a>
					</DBNavigationItem>
				</DBMainNavigation>
			</div>
		</template>
	</DefaultComponent>
</template>
