// showcases/react-showcase/src/components/textarea/index.tsx
import { useState } from 'react';
import { DBTextarea } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/textarea.json';
import type { DBTextareaProps } from '../../../../../output/react/src/components/textarea/model';
import { getVariants } from '../data';

const getTextarea = ({
	cols,
	disabled,
	message,
	label,
	placeholder,
	rows,
	value,
	variant,
	readOnly,
	required,
	children,
	invalid,
	labelVariant
}: DBTextareaProps) => {
	const [dynamicValue, setDynamicValue] = useState<string>(value);
	return (
		<DBTextarea
			cols={cols}
			disabled={disabled}
			message={message}
			label={label}
			labelVariant={labelVariant}
			readOnly={readOnly}
			onChange={(event) => {
				setDynamicValue(event.target.value);
			}}
			required={required}
			placeholder={placeholder ?? children}
			rows={rows}
			value={dynamicValue}
			variant={variant}
			invalid={invalid}></DBTextarea>
	);
};

const TextareaComponent = () => {
	return (
		<>
			<DefaultComponent
				title="DBTextarea"
				variants={getVariants(
					defaultComponentVariants,
					getTextarea
				)}></DefaultComponent>
		</>
	);
};

export default TextareaComponent;

// showcases/vue-showcase/src/components/textarea/Textarea.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/textarea.json";
import { DBTextarea } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBTextarea" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTextarea
				:cols="exampleProps.cols"
				:disabled="exampleProps.disabled"
				:message="exampleProps.message"
				:required="exampleProps.required"
				:readOnly="exampleProps.readOnly"
				:label="exampleProps.label"
				:labelVariant="exampleProps.labelVariant"
				:placeholder="exampleProps.placeholder || exampleName"
				:rows="exampleProps.rows"
				:value="exampleProps.value"
				:invalid="exampleProps.invalid"
				:variant="exampleProps.variant"
			></DBTextarea>
		</template>
	</DefaultComponent>
</template>
