// showcases/angular-showcase/src/app/components/checkbox/checkbox.component.ts
import { Component } from '@angular/core';
import { DBCheckbox } from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/checkbox.json';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-checkbox',
	templateUrl: './checkbox.component.html',
	imports: [DefaultComponent, DBCheckbox],
	standalone: true
})
export class CheckboxComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="Checkbox"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-checkbox
			[label]="exampleProps.label"
			[disabled]="exampleProps.disabled"
			[checked]="exampleProps.checked"
			[value]="exampleProps.value"
			[required]="exampleProps.required"
			[indeterminate]="exampleProps.indeterminate"
			[variant]="exampleProps.variant"
			[size]="exampleProps.size"
			>{{ exampleName }}</db-checkbox
		>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/checkbox/Checkbox.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/checkbox.json";
import { DBCheckbox } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="Checkbox" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCheckbox
				:label="exampleProps.label"
				:variant="exampleProps.variant"
				:options="exampleProps.options"
				:checked="exampleProps.checked"
				:disabled="exampleProps.disabled"
				:value="exampleProps.value"
				:required="exampleProps.required"
				:indeterminate="exampleProps.indeterminate"
				:size="exampleProps.size"
				>{{ exampleName }}</DBCheckbox
			>
		</template>
	</DefaultComponent>
</template>
