// showcases/angular-showcase/src/app/components/navigation/navigation.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/navigation.json';
import { DefaultComponent } from '../default.component';
import {
	DBNavigation,
	DBInfotext,
	DBNavigationItem,
	NavigationContentDirective
} from '../../../../../../output/angular/src';

@Component({
	selector: 'app-navigation',
	templateUrl: './navigation.component.html',
	imports: [
		DefaultComponent,
		DBNavigation,
		DBNavigationItem,
		NavigationContentDirective,
		DBInfotext
	],
	standalone: true
})
export class NavigationComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="db-navigation"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<div>
			<db-infotext size="small" semantic="informational" icon="none">
				{{ exampleName }}</db-infotext
			>
			<db-navigation>
				<db-navigation-item [active]="true">
					<ng-container *dbNavigationContent>
						Navi-Item 1
					</ng-container>
					<ng-container sub-navigation>
						<db-navigation-item [active]="true">
							<ng-container *dbNavigationContent>
								Sub-Navi-Item 1
							</ng-container>
							<ng-container sub-navigation>
								<db-navigation-item
									[active]="true"
									[areaPopup]="false"
								>
									<ng-container *dbNavigationContent>
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</ng-container>
								</db-navigation-item>
								<db-navigation-item [areaPopup]="false">
									<ng-container *dbNavigationContent>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</ng-container>
								</db-navigation-item>
							</ng-container>
						</db-navigation-item>
						<db-navigation-item [areaPopup]="false">
							<ng-container *dbNavigationContent>
								<a href="#">Sub-Navi-Item 2</a>
							</ng-container>
						</db-navigation-item>
					</ng-container>
				</db-navigation-item>
				<db-navigation-item icon="user" [areaPopup]="false">
					<ng-container *dbNavigationContent>
						<a href="#">Navi-Item 2</a>
					</ng-container>
				</db-navigation-item>
				<db-navigation-item [disabled]="true" [areaPopup]="false">
					<ng-container *dbNavigationContent>
						<a href="#">Navi-Item 3</a>
					</ng-container>
				</db-navigation-item>
			</db-navigation>
		</div>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/navigation/Navigation.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/navigation.json";
import {
	DBInfotext,
	DBNavigation,
	DBNavigationItem
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBNavigation" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<div>
				<DBInfotext size="small" semantic="informational" icon="none">
					{{ exampleName }}</DBInfotext
				>
				<DBNavigation>
					<DBNavigationItem :active="true">
						Navi-Item 1
						<template v-slot:sub-navigation>
							<DBNavigationItem :active="true">
								Sub-Navi-Item 1

								<template v-slot:sub-navigation>
									<DBNavigationItem :active="true">
										<a href="#">Sub-Sub-Navi-Item 1</a>
									</DBNavigationItem>
									<DBNavigationItem>
										<a href="#">Sub-Sub-Navi-Item 2</a>
									</DBNavigationItem>
								</template>
							</DBNavigationItem>
							<DBNavigationItem>
								<a href="#">Sub-Navi-Item 2</a>
							</DBNavigationItem>
						</template>
					</DBNavigationItem>
					<DBNavigationItem icon="user">
						<a href="#">Navi-Item 2</a>
					</DBNavigationItem>
					<DBNavigationItem :disabled="true">
						<a href="#">Navi-Item 3</a>
					</DBNavigationItem>
				</DBNavigation>
			</div>
		</template>
	</DefaultComponent>
</template>
