// showcases/vue-showcase/src/App.vue
<script setup lang="ts">
import {
	DBPage,
	DBHeader,
	DBBrand,
	DBSelect,
	DBNavigation,
	DBButton
} from "../../../output/vue/src";
import {
	COLORS,
	DENSITIES
} from "../../../packages/components/src/shared/constants";
import NavItemComponent from "./NavItemComponent.vue";

import { useLayout } from "./composables/use-layout";

const {
	page,
	fullscreen,
	density,
	color,
	drawerOpen,
	classNames,
	onChange,
	toggleDrawer,
	sortedNavigation
} = useLayout();
</script>

<template>
	<div v-if="page || fullscreen" :class="classNames">
		<router-view></router-view>
	</div>
	<DBPage
		v-if="!page && !fullscreen"
		variant="fixed"
		documentOverflow="auto"
		:fadeIn="true"
	>
		<template v-slot:header>
			<DBHeader :drawerOpen="drawerOpen" :onToggle="toggleDrawer">
				<template v-slot:brand>
					<DBBrand>Showcase</DBBrand>
				</template>
				<DBNavigation aria-label="main navigation">
					<template v-for="item of sortedNavigation">
						<NavItemComponent :navItem="item"></NavItemComponent>
					</template>
				</DBNavigation>
				<template v-slot:call-to-action>
					<DBButton
						icon="magnifying_glass"
						variant="ghost"
						:no-text="true"
					>
						Search
					</DBButton>
				</template>
				<template v-slot:action-bar>
					<DBButton icon="person" variant="ghost" :no-text="true">
						Profile
					</DBButton>
					<DBButton icon="bell" variant="ghost" :no-text="true">
						Notification
					</DBButton>
					<DBButton
						icon="question_mark_circle"
						variant="ghost"
						:no-text="true"
					>
						Help
					</DBButton>
				</template>
				<template v-slot:meta-navigation>
					<DBSelect
						label="Density"
						variant="floating"
						:value="density"
						@change="onChange($event, 'density')"
					>
						<option v-for="ton of DENSITIES" :value="ton">
							{{ ton }}
						</option>
					</DBSelect>
					<DBSelect
						label="Color"
						variant="floating"
						:value="color"
						@change="onChange($event, 'color')"
					>
						<option v-for="col of COLORS" :value="col">
							{{ col }}
						</option>
					</DBSelect>
				</template>
			</DBHeader>
		</template>
		<div :class="classNames">
			<router-view></router-view>
		</div>
	</DBPage>
</template>

// showcases/next-showcase/pages/_app.tsx
import { useState } from 'react';
import type { AppProps } from 'next/app';
import { DBBrand, DBButton, DBHeader, DBPage } from '../../../output/react/src';
import useQuery from '../../react-showcase/src/hooks/use-query';
import MetaNavigation from '../../react-showcase/src/meta-navigation';
import Navigation from '../../react-showcase/src/navigation';
import '../styles/global.scss';
import '../../showcase-styles.css';

const App = ({ Component, pageProps }: AppProps) => {
	const [density, setDensity, color, setColor, pageName, fullscreen] =
		useQuery();

	const [drawerOpen, setDrawerOpen] = useState<boolean>(false);

	if (pageName ?? fullscreen) {
		return (
			<div data-density={density} className={`db-${color}`}>
				<Component {...pageProps} />
			</div>
		);
	}

	return (
		<DBPage
			variant="fixed"
			documentOverflow="auto"
			fadeIn
			header={
				<DBHeader
					drawerOpen={drawerOpen}
					onToggle={setDrawerOpen}
					brand={<DBBrand>Showcase</DBBrand>}
					metaNavigation={
						<MetaNavigation
							onColorChange={setColor}
							onDensityChange={setDensity}
						/>
					}
					primaryAction={
						<DBButton
							icon="magnifying_glass"
							variant="ghost"
							noText>
							Search
						</DBButton>
					}
					secondaryAction={
						<>
							<DBButton icon="person" variant="ghost" noText>
								Profile
							</DBButton>
							<DBButton icon="bell" variant="ghost" noText>
								Notification
							</DBButton>
							<DBButton
								icon="question_mark_circle"
								variant="ghost"
								noText>
								Help
							</DBButton>
						</>
					}>
					<Navigation />
				</DBHeader>
			}>
			<div data-density={density} className={`db-${color}`}>
				<Component {...pageProps} />
			</div>
		</DBPage>
	);
};

export default App;
