// showcases/vue-showcase/src/components/checkbox/Checkbox.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/checkbox.json";
import { DBCheckbox } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="Checkbox" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCheckbox
				:label="exampleProps.label"
				:variant="exampleProps.variant"
				:options="exampleProps.options"
				:checked="exampleProps.checked"
				:disabled="exampleProps.disabled"
				:value="exampleProps.value"
				:required="exampleProps.required"
				:indeterminate="exampleProps.indeterminate"
				:invalid="exampleProps.invalid"
				:size="exampleProps.size"
				>{{ exampleName }}</DBCheckbox
			>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/checkbox/index.tsx
import { DBCheckbox } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import { getVariants } from '../data';
import defaultComponentVariants from '../../../../shared/checkbox.json';
import { type DBCheckboxProps } from '../../../../../output/react/src/components/checkbox/model';

const getCheckbox = ({
	label,
	size,
	name,
	checked,
	invalid,
	required,
	children,
	disabled,
	indeterminate
}: DBCheckboxProps) => (
	<DBCheckbox
		label={label}
		size={size}
		name={name}
		checked={checked}
		invalid={invalid}
		required={required}
		disabled={disabled}
		indeterminate={indeterminate}>
		{children}
	</DBCheckbox>
);

const CheckboxComponent = () => {
	return (
		<DefaultComponent
			title={'DBCheckbox'}
			variants={getVariants(
				defaultComponentVariants,
				getCheckbox
			)}></DefaultComponent>
	);
};

export default CheckboxComponent;
