// showcases/vue-showcase/src/components/card/Card.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/card.json";
import { DBCard } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBCard" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBCard
				:colorVariant="exampleProps.colorVariant"
				:variant="exampleProps.variant"
				:spacing="exampleProps.spacing"
			>
				<strong>{{ exampleName }}</strong>
				<span v-if="exampleProps.colorVariant">{{
					exampleProps.colorVariant
				}}</span>
			</DBCard>
		</template>
	</DefaultComponent>
</template>

// showcases/react-showcase/src/components/card/index.tsx
import { DBCard } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/card.json';
import { getVariants } from '../data';
import type { DBCardProps } from '../../../../../output/react/src/components/card/model';

const getCard = ({ colorVariant, variant, children, spacing }: DBCardProps) => (
	<DBCard colorVariant={colorVariant} variant={variant} spacing={spacing}>
		<strong>{children}</strong>
		{colorVariant && <span>{colorVariant}</span>}
	</DBCard>
);

const CardComponent = () => {
	return (
		<DefaultComponent
			title={'DBCard'}
			variants={getVariants(
				defaultComponentVariants,
				getCard
			)}></DefaultComponent>
	);
};

export default CardComponent;
