// showcases/react-showcase/src/components/section/index.tsx
import { DBSection } from '../../../../../output/react/src';
import DefaultComponent from '../default-component';
import defaultComponentVariants from '../../../../shared/section.json';
import { type DBSectionProps } from '../../../../../output/react/src/components/section/model';
import { getVariants } from '../data';
import { type BaseComponentProps } from '../base-component-data';

const getSection = ({ width, spacing, children }: DBSectionProps) => (
	<DBSection
		className="db-informational-bg-basic-level-2"
		spacing={spacing}
		width={width}>
		{children}
	</DBSection>
);

const SectionComponent = (props: BaseComponentProps) => {
	return (
		<DefaultComponent
			title={'DBSection'}
			variants={getVariants(
				defaultComponentVariants,
				getSection,
				props.slotCode
			)}></DefaultComponent>
	);
};

export default SectionComponent;

// showcases/vue-showcase/src/components/section/Section.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/section.json";
import { DBSection } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBSection" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBSection
				class="db-informational-bg-basic-level-2"
				:spacing="exampleProps?.spacing"
				:width="exampleProps?.width"
			>
				{{ exampleName }}
			</DBSection>
		</template>
	</DefaultComponent>
</template>
