// showcases/angular-showcase/src/app/components/popover/popover.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/popover.json';
import { DefaultComponent } from '../default.component';
import { DBButton, DBPopover } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-popover',
	templateUrl: './popover.component.html',
	imports: [DefaultComponent, DBPopover, DBButton],
	standalone: true
})
export class PopoverComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBPopover"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-popover
			[width]="exampleProps.width"
			[gap]="exampleProps.gap"
			[spacing]="exampleProps.spacing"
			[placement]="exampleProps.placement"
			[animation]="exampleProps.animation"
			[delay]="exampleProps.delay"
			[id]="exampleProps.id"
		>
			<db-button trigger>
				{{ exampleName }}
			</db-button>
			@if (exampleProps.content) {
				{{ exampleProps.content }}
			} @else {
				<ul class="popover-list">
					<li>Popover Custom Item 1</li>
					<li>Popover Custom Item 2</li>
				</ul>
				<db-button>Popover Custom Item 3</db-button>
			}
		</db-popover>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/popover/Popover.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/popover.json";
import { DBButton, DBPopover } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBPopover" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBPopover
				:width="exampleProps.width"
				:gap="exampleProps.gap"
				:spacing="exampleProps.spacing"
				:placement="exampleProps.placement"
				:animation="exampleProps.animation"
				:delay="exampleProps.delay"
				:id="exampleProps.id"
			>
				<template v-slot:trigger>
					<DBButton>
						{{ exampleName }}
					</DBButton>
				</template>
				<template v-if="exampleProps.content">{{
					exampleProps.content
				}}</template>
				<template v-if="!exampleProps.content">
					<ul class="popover-list">
						<li>Popover Custom Item 1</li>
						<li>Popover Custom Item 2</li>
					</ul>
					<DBButton>Popover Custom Item 3</DBButton>
				</template>
			</DBPopover>
		</template>
	</DefaultComponent>
</template>
