// showcases/angular-showcase/src/app/components/divider/divider.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/divider.json';
import { DefaultComponent } from '../default.component';
import { DBDivider, DBInfotext } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-divider',
	templateUrl: './divider.component.html',
	imports: [DefaultComponent, DBDivider, DBInfotext],
	standalone: true
})
export class DividerComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBDivider"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-infotext size="small" semantic="informational">
			{{ exampleName }}</db-infotext
		>
		<db-divider
			[variant]="exampleProps?.variant"
			[emphasis]="exampleProps?.emphasis"
			[width]="exampleProps?.width"
		>
		</db-divider>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/divider/Divider.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/divider.json";
import { DBDivider, DBInfotext } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBDivider" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBInfotext size="small" semantic="informational">
				{{ exampleName }}</DBInfotext
			>
			<DBDivider
				:variant="exampleProps?.variant"
				:emphasis="exampleProps?.emphasis"
				:width="exampleProps?.width"
			/>
		</template>
	</DefaultComponent>
</template>
