// showcases/nuxt-showcase/src/components/radio/Radio.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/radio.json";
import { DBRadio } from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBRadio" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBRadio
				:label="exampleProps.label"
				:size="exampleProps.size"
				:name="exampleProps.name"
				:checked="exampleProps.checked"
				:value="exampleProps.value"
				:required="exampleProps.required"
				:variant="exampleProps.variant"
				:disabled="exampleProps.disabled"
			>
				{{ exampleName }}
			</DBRadio>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/radio/radio.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/radio.json';
import { DefaultComponent } from '../default.component';
import { DBRadio } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-radio',
	templateUrl: './radio.component.html',
	imports: [DefaultComponent, DBRadio],
	standalone: true
})
export class RadioComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBLink"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-radio
			[label]="exampleProps.label"
			[size]="exampleProps.size"
			[name]="exampleProps.name"
			[value]="exampleProps.value"
			[checked]="exampleProps.checked"
			[required]="exampleProps.required"
			[disabled]="exampleProps.disabled"
			[variant]="exampleProps.variant"
		>
			{{ exampleName }}
		</db-radio>
	</ng-template>
</app-default-component>
