// showcases/angular-showcase/src/app/components/link/link.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/link.json';
import { DefaultComponent } from '../default.component';
import { DBLink } from '../../../../../../output/angular/src';

@Component({
	selector: 'app-link',
	templateUrl: './link.component.html',
	imports: [DefaultComponent, DBLink],
	standalone: true
})
export class LinkComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="Link"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<db-link *ngIf="exampleIndex === 0" href="#">{{ exampleName }}</db-link>
		<ng-container *ngIf="exampleIndex === 1 && variantIndex === 0">
			<db-link variant="primary" href="#">{{ exampleName }}</db-link>
		</ng-container>
		<ng-container *ngIf="exampleIndex === 1 && variantIndex === 1">
			<db-link [disabled]="true">{{ exampleName }}</db-link>
		</ng-container>
		<ng-container *ngIf="exampleIndex === 1 && variantIndex === 2">
			<db-link size="small">{{ exampleName }}</db-link>
		</ng-container>
		<ng-container *ngIf="exampleIndex === 1 && variantIndex === 3">
			<db-link content="external">{{ exampleName }}</db-link>
		</ng-container>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/link/Link.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/link.json";
import { DBLink } from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="Link" :variants="defaultComponentVariants">
		<template #example="{ exampleIndex, variantIndex, exampleName }">
			<template v-if="exampleIndex === 0">
				<DBLink href="#">{{ exampleName }}</DBLink>
			</template>
			<template v-if="exampleIndex === 1 && variantIndex === 0">
				<DBLink href="#" variant="primary">{{ exampleName }}</DBLink>
			</template>

			<template v-if="exampleIndex === 1 && variantIndex === 1">
				<DBLink href="#" disabled="true">{{ exampleName }}</DBLink>
			</template>

			<template v-if="exampleIndex === 1 && variantIndex === 2">
				<DBLink href="#" size="small">{{ exampleName }}</DBLink>
			</template>

			<template v-if="exampleIndex === 1 && variantIndex === 3">
				<DBLink href="#" content="external">{{ exampleName }}</DBLink>
			</template>
		</template>
	</DefaultComponent>
</template>
