// showcases/nuxt-showcase/src/components/tabs/Tabs.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tabs.json";
import {
	DBTabs,
	DBInfotext,
	DBTabList,
	DBTabItem,
	DBTabPanel
} from "../../../../../output/vue/src";
</script>

<template>
	<DefaultComponent title="DBTabs" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<div class="w-full">
				<DBInfotext icon="none" size="small" semantic="informational">
					{{ exampleName }}:
				</DBInfotext>
				<DBTabs
					:orientation="exampleProps.orientation"
					:width="exampleProps.width"
					:alignment="exampleProps.alignment"
					:behaviour="exampleProps.behaviour"
					:initialSelectedIndex="exampleProps.initialSelectedIndex"
					:initialSelectedMode="exampleProps.initialSelectedMode"
					:arrowScrollDistance="75"
				>
					<DBTabList>
						<DBTabItem> Test 1 </DBTabItem>
						<DBTabItem> Test 2 </DBTabItem>
						<DBTabItem> Test 3 </DBTabItem>
						<template v-if="exampleProps.overflow">
							<DBTabItem> Test 4 </DBTabItem>
							<DBTabItem> Test 5 </DBTabItem>
						</template>
					</DBTabList>
					<DBTabPanel> Tab Panel 1 </DBTabPanel>
					<DBTabPanel> Tab Panel 2 </DBTabPanel>
					<DBTabPanel> Tab Panel 3 </DBTabPanel>
					<template v-if="exampleProps.overflow">
						<DBTabPanel> Tab Panel 4 </DBTabPanel>
						<DBTabPanel> Tab Panel 5 </DBTabPanel>
					</template>
				</DBTabs>
			</div>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/tabs/tabs.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tabs.json';
import { DefaultComponent } from '../default.component';
import {
	DBInfotext,
	DBTabItem,
	DBTabList,
	DBTabPanel,
	DBTabs
} from '../../../../../../output/angular/src';

@Component({
	selector: 'app-tabs',
	templateUrl: './tabs.component.html',
	imports: [
		DefaultComponent,
		DBTabs,
		DBTabItem,
		DBTabList,
		DBTabPanel,
		DBInfotext
	],
	standalone: true
})
export class TabsComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBTabs"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<div class="w-full">
			<db-infotext icon="none" size="small" semantic="informational">
				{{ exampleName }}:
			</db-infotext>
			<db-tabs
				[orientation]="exampleProps.orientation"
				[width]="exampleProps.width"
				[alignment]="exampleProps.alignment"
				[behaviour]="exampleProps.behaviour"
				[initialSelectedIndex]="exampleProps.initialSelectedIndex"
				[initialSelectedMode]="exampleProps.initialSelectedMode"
				[arrowScrollDistance]="75"
			>
				<db-tab-list>
					<db-tab-item>Test 1</db-tab-item>
					<db-tab-item>Test 2</db-tab-item>
					<db-tab-item>Test 3</db-tab-item>
					@if (exampleProps.overflow) {
						<db-tab-item>Test 4</db-tab-item>
						<db-tab-item>Test 5</db-tab-item>
					}
				</db-tab-list>
				<db-tab-panel> Tab Panel 1 </db-tab-panel>
				<db-tab-panel> Tab Panel 2 </db-tab-panel>
				<db-tab-panel> Tab Panel 3 </db-tab-panel>

				@if (exampleProps.overflow) {
					<db-tab-panel> Tab Panel 4 </db-tab-panel>
					<db-tab-panel> Tab Panel 5 </db-tab-panel>
				}
			</db-tabs>
		</div>
	</ng-template>
</app-default-component>
