// showcases/vue-showcase/src/components/badge/Badge.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/badge.json";
import {
	DBBadge,
	DBIcon,
	DBButton,
	DBInfotext
} from "../../../../../output/vue/vue3/src";
</script>

<template>
	<DefaultComponent title="DBBadge" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<template v-if="!exampleProps.placement && !exampleProps.example">
				<DBBadge
					:variant="exampleProps.variant"
					:emphasis="exampleProps.emphasis"
					:size="exampleProps.size"
				>
					{{ exampleProps.noContent ? "" : exampleName }}
				</DBBadge>
				<DBInfotext
					v-if="exampleProps.noContent"
					variant="informational"
					size="small"
					icon="none"
				>
					{{ exampleName }}
				</DBInfotext>
			</template>

			<template
				v-if="
					exampleProps.placement &&
					exampleProps.placement !== 'inline' &&
					!exampleProps.example
				"
			>
				<DBButton icon="account" variant="outlined" :noText="true">
					<DBBadge
						emphasis="strong"
						variant="critical"
						size="small"
						:placement="exampleProps.placement"
					>
					</DBBadge>
					{{ exampleName }}
				</DBButton>
				<DBInfotext variant="informational" size="small" icon="none">
					{{ exampleName }}
				</DBInfotext>
			</template>

			<template v-if="exampleProps.placement === 'inline'">
				<div class="badge-inline-container">
					<DBIcon icon="account"></DBIcon>
					<span>{{ exampleName }}</span>
					<DBBadge size="small" emphasis="strong" variant="critical">
						Label
					</DBBadge>
					<DBIcon icon="error"></DBIcon>
				</div>
			</template>

			<template v-if="exampleProps.example === 'icon'">
				<DBBadge
					variant="critical"
					emphasis="strong"
					:size="exampleProps.size"
				>
					<DBIcon icon="account">{{ exampleName }}</DBIcon>
				</DBBadge>
				<DBInfotext variant="informational" size="small" icon="none">
					{{ exampleName }}
				</DBInfotext>
			</template>

			<template v-if="exampleProps.example === 'number'">
				<DBBadge variant="successful">9</DBBadge>
				<DBBadge variant="informational">12</DBBadge>
				<DBBadge variant="warning">123</DBBadge>
				<DBBadge size="small" emphasis="strong" variant="successful">
					9
				</DBBadge>
				<DBBadge size="small" emphasis="strong" variant="informational">
					12
				</DBBadge>
				<DBBadge size="small" emphasis="strong" variant="warning">
					123
				</DBBadge>
				<DBInfotext variant="informational" size="small" icon="none">
					{{ exampleName }}
				</DBInfotext>
			</template>
		</template>
	</DefaultComponent>
</template>

// showcases/angular-showcase/src/app/components/badge/badge.component.ts
import { Component } from '@angular/core';
import {
	DBBadge,
	DBButton,
	DBIcon,
	DBInfotext
} from '../../../../../../output/angular/src';
import defaultComponentVariants from '../../../../../shared/badge.json';
import { DefaultComponent } from '../default.component';

@Component({
	selector: 'app-badge',
	templateUrl: './badge.component.html',
	imports: [DefaultComponent, DBBadge, DBInfotext, DBButton, DBIcon],
	standalone: true
})
export class BadgeComponent {
	variants = defaultComponentVariants;
}

<app-default-component
	title="DBBadge"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
		let-exampleIndex="exampleIndex"
		let-variantIndex="variantIndex"
	>
		<ng-container *ngIf="!exampleProps.placement && !exampleProps.example">
			<db-badge
				[variant]="exampleProps.variant"
				[emphasis]="exampleProps.emphasis"
				[size]="exampleProps.size"
				>{{ exampleProps.noContent ? "" : exampleName }}</db-badge
			>
			<db-infotext
				*ngIf="exampleProps.noContent"
				variant="informational"
				size="small"
				icon="none"
			>
				{{ exampleName }}
			</db-infotext>
		</ng-container>

		<ng-container
			*ngIf="
				exampleProps.placement &&
				exampleProps.placement !== 'inline' &&
				!exampleProps.example
			"
		>
			<db-button icon="account" variant="outlined" [noText]="true">
				<db-badge
					emphasis="strong"
					variant="critical"
					size="small"
					[placement]="exampleProps.placement"
				></db-badge>
				{{ exampleName }}
			</db-button>
			<db-infotext variant="informational" size="small" icon="none">
				{{ exampleName }}
			</db-infotext>
		</ng-container>

		<ng-container *ngIf="exampleProps.placement === 'inline'">
			<div class="badge-inline-container">
				<db-icon icon="account"></db-icon>
				<span>{{ exampleName }}</span>
				<db-badge size="small" emphasis="strong" variant="critical">
					Label
				</db-badge>
				<db-icon icon="error"></db-icon>
			</div>
		</ng-container>

		<ng-container *ngIf="exampleProps.example === 'icon'">
			<db-badge
				variant="critical"
				emphasis="strong"
				[size]="exampleProps.size"
			>
				<db-icon icon="account">{{ exampleName }}</db-icon>
			</db-badge>
			<db-infotext variant="informational" size="small" icon="none">
				{{ exampleName }}
			</db-infotext>
		</ng-container>

		<ng-container *ngIf="exampleProps.example === 'number'">
			<db-badge variant="successful">9</db-badge>
			<db-badge variant="informational">12</db-badge>
			<db-badge variant="warning">123</db-badge>
			<db-badge size="small" emphasis="strong" variant="successful">
				9
			</db-badge>
			<db-badge size="small" emphasis="strong" variant="informational">
				12
			</db-badge>
			<db-badge size="small" emphasis="strong" variant="warning">
				123
			</db-badge>
			<db-infotext variant="informational" size="small" icon="none">
				{{ exampleName }}
			</db-infotext></ng-container
		>
	</ng-template>
</app-default-component>
