// showcases/react-showcase/src/components/notification/index.tsx
import { DBNotification, DBLink } from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/notification.json';
import { type DBNotificationProps } from '../../../../../output/react/src/components/notification/model';
import { getVariants } from '../data';
import { getBasePath } from '../../utils/base-path';

const getNotification = ({
	semantic,
	icon,
	headline,
	variant,
	children,
	behaviour,
	link,
	timestamp,
	linkVariant,
	img
}: DBNotificationProps & { link: boolean; img: boolean }) => (
	<DBNotification
		semantic={semantic}
		icon={icon}
		headline={headline}
		link={link ? <DBLink href="#">Textlink</DBLink> : undefined}
		image={
			img ? (
				<img
					src={`${getBasePath()}/assets/images/placeholder.jpg`}
					alt="Placeholder"
				/>
			) : undefined
		}
		variant={variant}
		behaviour={behaviour}
		linkVariant={linkVariant}
		timestamp={timestamp}
		onClose={() => {
			// eslint-disable-next-line no-alert
			alert(children.toString());
		}}>
		{children}
	</DBNotification>
);

const NotificationComponent = () => {
	return (
		<DefaultComponent
			title="DBNotification"
			variants={getVariants(
				defaultComponentVariants,
				getNotification
			)}></DefaultComponent>
	);
};

export default NotificationComponent;

// showcases/vue-showcase/src/components/notification/Notification.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/notification.json";
import { DBNotification, DBLink } from "../../../../../output/vue/src";

const log = (exampleName: string) => {
	// eslint-disable-next-line no-notification
	alert(exampleName);
};
</script>

<template>
	<DefaultComponent
		title="DBNotification"
		:variants="defaultComponentVariants"
	>
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBNotification
				:semantic="exampleProps.semantic"
				:headline="exampleProps.headline"
				:variant="exampleProps.variant"
				:link-variant="exampleProps.linkVariant"
				:timestamp="exampleProps.timestamp"
				:icon="exampleProps.icon"
				:behaviour="exampleProps.behaviour"
				@onClose="log(exampleName)"
			>
				<template v-if="exampleProps.link" v-slot:link>
					<DBLink href="#">Textlink</DBLink>
				</template>
				<template v-if="exampleProps.img" v-slot:image>
					<img
						src="/assets/images/placeholder.jpg"
						alt="Placeholder"
					/>
				</template>
				{{ exampleName }}
			</DBNotification>
		</template>
	</DefaultComponent>
</template>
