// showcases/react-showcase/src/components/tag/index.tsx
import { useState } from 'react';
import {
	DBButton,
	DBCheckbox,
	DBLink,
	DBRadio,
	DBTag
} from '../../../../../output/react/src';
import DefaultComponent from '../index';
import defaultComponentVariants from '../../../../shared/tag.json';
import { type DBTagProps } from '../../../../../output/react/src/components/tag/model';
import { getVariants } from '../data';

const getTag = ({
	semantic,
	disabled,
	children,
	icon,
	overflow,
	noText,
	behaviour,
	emphasis,
	removeButton,
	checked,
	component
}: DBTagProps & {
	checked?: boolean;
	component?: 'button' | 'link' | 'radio' | 'checkbox';
}) => {
	const [checkedState, setCheckedState] = useState<boolean>(checked ?? false);
	return (
		<DBTag
			semantic={semantic}
			disabled={disabled}
			icon={icon}
			noText={noText}
			behaviour={behaviour}
			emphasis={emphasis}
			overflow={overflow}
			removeButton={removeButton}
			onRemove={() => {
				// eslint-disable-next-line no-alert
				alert(children.toString());
			}}>
			{component === 'button' && <DBButton>{children}</DBButton>}
			{component === 'link' && <DBLink href="#">{children}</DBLink>}
			{component === 'checkbox' && (
				<DBCheckbox
					checked={checkedState}
					onChange={(event) => {
						setCheckedState(event.target.checked);
					}}>
					{children}
				</DBCheckbox>
			)}
			{component === 'radio' && (
				<DBRadio checked={checked} name="radio">
					{children}
				</DBRadio>
			)}

			{!component && !overflow && <>{children}</>}
			{!component && overflow && <span>{children}</span>}
		</DBTag>
	);
};

const TagComponent = () => {
	return (
		<DefaultComponent
			title="DBTag"
			variants={getVariants(
				defaultComponentVariants,
				getTag
			)}></DefaultComponent>
	);
};

export default TagComponent;

// showcases/angular-showcase/src/app/components/tag/tag.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tag.json';
import { DefaultComponent } from '../default.component';
import { DBTag } from '../../../../../../output/angular/src/components/tag/tag';
import { DBButton } from '../../../../../../output/angular/src/components/button';
import { DBCheckbox } from '../../../../../../output/angular/src/components/checkbox/checkbox';
import { DBRadio } from '../../../../../../output/angular/src/components/radio/radio';
import { DBLink } from '../../../../../../output/angular/src/components/link';

@Component({
	selector: 'app-tag',
	templateUrl: './tag.component.html',
	imports: [DefaultComponent, DBTag, DBButton, DBCheckbox, DBRadio, DBLink],
	standalone: true
})
export class TagComponent {
	variants = defaultComponentVariants;
	showAlert = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<app-default-component
	title="DBTag"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
	>
		<db-tag
			[semantic]="exampleProps.semantic"
			[disabled]="exampleProps.disabled"
			[icon]="exampleProps.icon"
			[noText]="exampleProps.noText"
			[behaviour]="exampleProps.behaviour"
			[emphasis]="exampleProps.emphasis"
			[overflow]="exampleProps.overflow"
			[removeButton]="exampleProps.removeButton"
			(onRemove)="showAlert(exampleName)"
		>
			@if (exampleProps.component === "button") {
				<db-button>{{ exampleName }}</db-button>
			}
			@if (exampleProps.component === "link") {
				<db-link href="#">
					{{ exampleName }}
				</db-link>
			}
			@if (exampleProps.component === "checkbox") {
				<db-checkbox [checked]="exampleProps.checked">{{
					exampleName
				}}</db-checkbox>
			}
			@if (exampleProps.component === "radio") {
				<db-radio name="radio" [checked]="exampleProps.checked">{{
					exampleName
				}}</db-radio>
			}
			@if (!exampleProps.component && !exampleProps.overflow) {
				{{ exampleName }}
			}
			@if (!exampleProps.component && exampleProps.overflow) {
				<span>{{ exampleName }}</span>
			}
		</db-tag>
	</ng-template>
</app-default-component>
