// showcases/angular-showcase/src/app/components/tag/tag.component.ts
import { Component } from '@angular/core';
import defaultComponentVariants from '../../../../../shared/tag.json';
import { DefaultComponent } from '../default.component';
import {
	DBButton,
	DBCheckbox,
	DBLink,
	DBRadio,
	DBTag
} from '../../../../../../output/angular/src';

@Component({
	selector: 'app-tag',
	templateUrl: './tag.component.html',
	imports: [DefaultComponent, DBTag, DBButton, DBCheckbox, DBRadio, DBLink],
	standalone: true
})
export class TagComponent {
	variants = defaultComponentVariants;
	showAlert = (exampleName: string) => {
		// eslint-disable-next-line no-alert
		alert(exampleName);
	};
}

<app-default-component
	title="DBTag"
	[variants]="variants"
	[exampleTemplate]="exampleTemplate"
>
	<ng-template
		#exampleTemplate
		let-exampleProps="exampleProps"
		let-exampleName="exampleName"
	>
		<db-tag
			[semantic]="exampleProps.semantic"
			[disabled]="exampleProps.disabled"
			[icon]="exampleProps.icon"
			[noText]="exampleProps.noText"
			[behaviour]="exampleProps.behaviour"
			[emphasis]="exampleProps.emphasis"
			[overflow]="exampleProps.overflow"
			[removeButton]="exampleProps.removeButton"
			(onRemove)="showAlert(exampleName)"
		>
			@if (exampleProps.component === "button") {
				<db-button>{{ exampleName }}</db-button>
			}
			@if (exampleProps.component === "link") {
				<db-link href="#">
					{{ exampleName }}
				</db-link>
			}
			@if (exampleProps.component === "checkbox") {
				<db-checkbox [checked]="exampleProps.checked">{{
					exampleName
				}}</db-checkbox>
			}
			@if (exampleProps.component === "radio") {
				<db-radio name="radio" [checked]="exampleProps.checked">{{
					exampleName
				}}</db-radio>
			}
			@if (!exampleProps.component && !exampleProps.overflow) {
				{{ exampleName }}
			}
			@if (!exampleProps.component && exampleProps.overflow) {
				<span>{{ exampleName }}</span>
			}
		</db-tag>
	</ng-template>
</app-default-component>

// showcases/vue-showcase/src/components/tag/Tag.vue
<script setup lang="ts">
import DefaultComponent from "../DefaultComponent.vue";
import defaultComponentVariants from "../../../../shared/tag.json";
import {
	DBTag,
	DBButton,
	DBLink,
	DBCheckbox,
	DBRadio
} from "../../../../../output/vue/src";

const showAlert = (exampleName?: string) => {
	// eslint-disable-next-line no-alert
	alert(exampleName || "");
};
</script>

<template>
	<DefaultComponent title="DBTag" :variants="defaultComponentVariants">
		<template
			#example="{ exampleIndex, variantIndex, exampleName, exampleProps }"
		>
			<DBTag
				:semantic="exampleProps.semantic"
				:disabled="exampleProps.disabled"
				:icon="exampleProps.icon"
				:noText="exampleProps.noText"
				:behaviour="exampleProps.behaviour"
				:emphasis="exampleProps.emphasis"
				:overflow="exampleProps.overflow"
				:removeButton="exampleProps.removeButton"
				@remove="showAlert(exampleName)"
			>
				<DBButton v-if="exampleProps.component === 'button'">{{
					exampleName
				}}</DBButton>
				<DBLink v-if="exampleProps.component === 'link'" href="#">
					{{ exampleName }}
				</DBLink>
				<DBCheckbox
					v-if="exampleProps.component === 'checkbox'"
					:checked="exampleProps.checked"
					>{{ exampleName }}</DBCheckbox
				>
				<DBRadio
					v-if="exampleProps.component === 'radio'"
					name="radio"
					:checked="exampleProps.checked"
					>{{ exampleName }}</DBRadio
				>
				<template
					v-if="
						exampleProps.component !== 'button' &&
						exampleProps.component !== 'link' &&
						exampleProps.component !== 'checkbox' &&
						exampleProps.component !== 'radio' &&
						!exampleProps.overflow
					"
				>
					{{ exampleName }}
				</template>
				<template
					v-if="
						exampleProps.component !== 'button' &&
						exampleProps.component !== 'link' &&
						exampleProps.component !== 'checkbox' &&
						exampleProps.component !== 'radio' &&
						exampleProps.overflow
					"
				>
					<span>{{ exampleName }}</span>
				</template>
			</DBTag>
		</template>
	</DefaultComponent>
</template>
