// showcases/react-showcase/src/App.tsx
import {
	DBButton,
	DBIcon,
	DBTabBar,
	DBTab
} from "../../../packages/core/output/react/src";

function App() {
	return (
		<main>
			<h1>React</h1>
			<div style={{ display: "flex", gap: "4px", alignItems: "center" }}>
				<DBButton variant="secondary">Test</DBButton>
				<DBButton text="Test" icon="account" />
				<DBIcon icon="account" />
			</div>

			<div
				style={{ display: "flex", gap: "4px", flexDirection: "column" }}
			>
				<h2>TabBar</h2>
				<DBTabBar>
					<DBTab name="tab-bar-1" label="Tab1">
						<strong>Content 1-1</strong>
					</DBTab>
					<DBTab name="tab-bar-1" label="Tab2" active={true}>
						Content 1-2
					</DBTab>
				</DBTabBar>

				<DBTabBar
					tabs={[
						{
							name: "tab-bar-2",
							label: "2-Tab1",
							active: true,
							children: <strong>Content 2-1</strong>
						},
						{
							name: "tab-bar-2",
							label: "2-Tab2",
							content: "Content 2-2"
						}
					]}
				/>
			</div>
		</main>
	);
}

export default App;

// showcases/angular-showcase/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
})
export class AppComponent {
  title = 'angular-showcase';

  tabs = [
    {
      name: 'tab-bar-2',
      label: '2-Tab1',
      active: true,
      children: 'Content 2-1',
    },
    { name: 'tab-bar-2', label: '2-Tab2', content: 'Content 2-2' },
  ];
}

<main>
  <h1>Angular</h1>
  <div style="display: flex; gap: 4px; align-items: center">
    <DBButton variant="secondary">Test</DBButton>
    <DBButton text="Test" icon="account"></DBButton>
    <DBIcon icon="account"></DBIcon>
  </div>

  <div style="display: flex; gap: 4px; flex-direction: column">
    <h2>TabBar</h2>
    <DBTabBar>
      <DBTab name="tab-bar-1" label="Tab1">
        <strong>Content 1-1</strong>
      </DBTab>
      <DBTab name="tab-bar-1" label="Tab2" [active]="true"> Content 1-2 </DBTab>
    </DBTabBar>

    <DBTabBar [tabs]="tabs"></DBTabBar>
  </div>
</main>
